### ISSUE TITLE
Add zMenu support for Inventory

### ISSUE THREAD

**Issue by Maxlego08** [Wuason6x9/StorageMechanic#2]
[zMenu](https://www.spigotmc.org/resources/zmenu-ultra-complete-menu-plugin.110402/) is an ultra complete inventory management plugin and has a very complete API.

Why add zMenu ?
Adding zMenu will allow you to simplify your code while increasing functionality for you and your customers.

You can add zMenu in addition to your current system, which allows your users to choose how to configure the plugin.

Documentation: https://docs.zmenu.dev/api/informations

**Comment by Wuason6x9** [comment]
I'm sorry, but I already have my own API that allows me to create anvil inventories in addition to multipages with multiple inventories within them. I'm not interested, thank you very much for the offer!
